services:
  db:
    image: postgres:17.4
    container_name: postgres-db
    environment:
      POSTGRES_DB: gosocial
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data: